### PR TITLE
Fix Small Peak calculation

### PR DESCRIPTION
**Pull request by brisberg**
I believe this fixes a bug with the prediction for the peak during a  "Small Peak" Pattern.

Right now, the prediction will special case the "middle" cell of the top of the peak. Limiting the max/min to exactly the reported value (and consequently raising the `guaranteed min` to this value). However, after 1 week of testing, I am not certain this is the case. My two friends did not have the highest price for the week on the "middle" cell.

The wiki claims that each day during the "peak" will have random values between 140% and 200% of base price. (Which matches the prediction before you fill in the middle cell).

The output predictions match my data much better and are much simpler than w/e the current if structure represents.

On Live:
Screen Shot 2020-05-15 at 11 19 44 PM

After this change:
Screen Shot 2020-05-15 at 11 19 52 PM

---

Ran `wasm-pack` to rebuild the pkg binary.

### CODE REVIEW

**Comment by elxris** [comment]
Thank you for the PR. However, I was intrigued by your numbers. I think they don't add up.
Let's do some math. With Ninji's code.
```
    sellPrices[work++] = intceil(randfloat(0.9, 1.4) * (float)basePrice);
    sellPrices[work++] = intceil(randfloat(0.9, 1.4) * basePrice);
    rate = randfloat(1.4, 2.0);
    sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
    sellPrices[work++] = intceil(rate * basePrice);
    sellPrices[work++] = intceil(randfloat(1.4, rate) * basePrice) - 1;
```
We know that youre not in the decreasing pattern at Tue PM. So the first sellPrices we see here is Tue PM.

As far as we know, your max for Thu PM should be `(2.0 * basePrice) - 1 `, and that's `199` not `200`.
The other thing is if we see 200 for Thu PM, that means that you got lucky and got the 2.0
That means that for Thu AM your price should be 200. Not 150. `rate * basePrice`.

If we try to estimate your rate we could follow the following logic:
Prevprice is Thu AM: 150
```
      // rate = ??;
      // sellPrices[prev] = prevRate * basePrice = prevPrice; 
      // rate = prevRate = prevPrice / basePrice;
```
If we do math, 150 / 100 is 1.5. Wich means that your possible max for Thu PM is `1.5 * basePrice - 1` = 149. Wich is not 200.

For now, we don't have enough information on why your numbers are like this. All the other calculators work the same.

**Comment by brisberg** [comment]
All the other calculators are all based on the same gist of Ninji's code. Base on his code as written, I agree that Thursday AM should always be the max price (2x base price).

I'm not convinced that is the case, but I'll wait another week or so of price gathering to determine it.

--

In either case though, I think there is still a bug in the pattern prediction which is makes its intent not at all clear.

For example, by entering all prices up to the start of the peak, the predicted space looks very reasonable. And the guaranteed minimum is 140 (the expected lower bound of the peak).

Screen Shot 2020-05-17 at 1 54 24 PM

However, when you a price for the middle of the peak (Thur AM) the probability for the peak shrinks to a range of 0. The guaranteed price rises to w/e price entered for Thur AM. And the max cap on the next day is limited to the middle peak price.

Screen Shot 2020-05-17 at 1 54 03 PM

Is this expected behavior?

**Comment by elxris** [comment]
It is expected behavior.

So, for example, if you had 150 on Thursday AM, we now know the rate that was used to calculate the max for the previous day (Wed PM) and the max for the next price point (Thu PM). The rate is 1.5. So the ranges for Wed PM and Thu PM, are 1.4 to 1.5. (Pretty small range).

**Comment by brisberg** [comment]
Hmm, so as a consequence: the highest price for a small peak will `always` be on the middle day of the small peak?

I'll close this PR for now. Though I'm suspicious if that actually is the case. I might reopen it if I see more contrary behavior in the wild.

**Comment by elxris** [comment]
Yeah. That would be the consequence.

Please come back if you confirm your suspicions. I would love to see that data.

**Pull request closed without merging**
