### PR TITLE
Fix share

### PR DESCRIPTION
**Pull request by KevinZjYang**
UWP webview does not support "trimEnd",this causes the sharing function to not work properly.
So I replaced it with “replace(/(\s*$)/g,"")”.Currently working fine.

### CODE REVIEW

**Comment by ysc3839** [comment]
Try using `trimRight`? https://caniuse.com/#feat=mdn-javascript_builtins_string_trimend

**Comment by KevinZjYang** [comment]
> Try using `trimRight`? https://caniuse.com/#feat=mdn-javascript_builtins_string_trimend

Yes, "trimRight" works.

**Comment by elxris** [comment]
Thank you a lot, didn't know about trimEnd compatibility.

**Comment by elxris** [comment]
I am deploying 1.8.1a which contains the fix.

**Pull request closed without merging**
