### PR TITLE
Add confirmation before clearing data

### PR DESCRIPTION
**Pull request by dstaley**
This PR adds a confirmation before clearing data. This prevents accidental deletion of data (something I, unfortunately, ran into myself!)

The i18n library falls back to English anyway, so I went ahead and added the key to all the locales to make it a little easier on translators.

### CODE REVIEW

**Comment by elxris** [comment]
Thank you! I think it would be nice to have it as a modal. Do you want to try it?

**Comment by dstaley** [comment]
@elxris Sure! I've used [SweetAlert2](https://sweetalert2.github.io/) in the past. Does that look okay, or would you prefer I use something a bit more low-level like [react-modal](https://github.com/reactjs/react-modal)?

**Comment by elxris** [comment]
We already use Material-UI
https://material-ui.com/components/modal/

Would this be ok?

**Comment by dstaley** [comment]
Oh, even better! That should be simple then.

**Comment by dstaley** [comment]
Which would you prefer:

Option One:
image

Option Two:
image

I prefer the version with the title, but the default font makes it look a bit weird. I can override the font if you prefer option one but with the default body font.

**Comment by elxris** [comment]
I think the second one is simpler.
But yeah, I think we can use the first.

**Comment by dstaley** [comment]
Alright this is ready!

**Pull request merged**
