### PR TITLE
Replace dollar with bell to represent currency

### PR DESCRIPTION
**Pull request by alyphen**
The calculator currently uses $ to represent currency, which doesn't match the currency used in game (bells). Proposing changing the currency symbol to bells to match that used in game.

### CODE REVIEW

**Comment by elxris** [comment]
I love this! Haha
But, bells aren't represented with stars like the ones in the coins or money bags?
I haven't seen a bell (actual bell) in the game.

**Comment by alyphen** [comment]
That's correct - could alternatively use:
* ⭐
*,💰
* Replace text with an actual bell bag graphic?

**Comment by elxris** [comment]
I'm not seeing the coin. That's a good indicator that we should use the coin emoji.
A custom bell graphic would be nice.
But, from the emoji options, I like the money bag the best.

**Comment by alyphen** [comment]
I've replaced it with an image, it now looks like this:
Screenshot of turnip calculator with bells icon

**Comment by elxris** [comment]
Thank you! I love it!

**Pull request merged**
